Nombre = input("Ingrese su nombre: ")
Apellido = input("Ingrese su apellido: ")
Rut = input("Ingrese su rut: ")
Duoc_mail = input("Ingrese su correo Duoc: ")
Duoc_sede = input("Ingrese su sede correspondiente: ")
print("Su nombre y apellido son " + Nombre, Apellido + " su rut es " + Rut + " Su correo Duoc es " + Duoc_mail + " y pertence a la sede " + Duoc_sede)
